### ISSUE TITLE
Multi-Cursor Mode

### ISSUE THREAD

**Issue by izlence** [ryu1kn/vscode-edit-with-shell#11]
Hello. This is an exciting extension. :+1: 

I have spend about 7 hours to be able to change the case of selected text to title case format using Turkish locale in VS Code. But I couldn't do that. 

Then using this great extension, it became very easy.  Here is the command I use:
LC_ALL=tr_TR.UTF-8 sed 's/[^ ]\+/\L\u&/g'

But it doesn't work in multi-cursor mode. Only the first selection transforming.

It would be excellent if you could support Multi-Cursor mode.

Thanks.

**Comment by ryu1kn** [comment]
Thanks @izlence for the suggestion. I agree, I think it's reasonable to assume that it should work with multi selection.

We would execute the shell command per selection and update the selection only when all the execution finished successfully.

**Comment by ryu1kn** [comment]
Released as v1.2.0 :tada:

**Comment by izlence** [comment]
This is great! Thank you so much! :+1:
