### ISSUE TITLE
Command to clear history

### ISSUE THREAD

**Issue by alexreg** [ryu1kn/vscode-edit-with-shell#4]
The history feature is quite useful, but if it gets cluttered, it might be useful to have a command to clear it. Would you kindly be able to add this?

**Comment by ryu1kn** [comment]
Hi @alexreg , thanks for the suggestion.

Are you thinking to remove all history at once or only remove part of it? The first can be easily done but the latter may need to wait for the multi select capability on quick pick UI which seems to be coming shortly.

**Comment by alexreg** [comment]
Oh, I see. How can the first be done right now? The latter sounds good too, but would just be a bonus.

**Comment by ryu1kn** [comment]
[HistoryStore](https://github.com/ryu1kn/vscode-edit-with-shell/blob/dd5d6960443af046d80a979dd7a4e181c2caddd9/lib/history-store.js) keeps the history; so I would create `clear` method on it and introduce a new command that invokes the method.

**Comment by alexreg** [comment]
Oh okay, I thought you meant there's already a feature. Well, if you can add it and you don't find it too much work, would appreciate it!

**Comment by ryu1kn** [comment]
Released as v0.4.0! You can try it out 😉

**Comment by alexreg** [comment]
Works great for me. Thank you!

**Comment by ryu1kn** [comment]
Great. Thanks for confirming 👍
