### ISSUE TITLE
Request: If no text currently selected, use whole file.

### ISSUE THREAD

**Issue by jgreer** [ryu1kn/vscode-edit-with-shell#5]
I use a command like this in TextMate all the time (100+ times per day), and most of the time I'm just trying to filter the current file with grep / cut / sort / etc.  So usually I don't want to select just a portion of the file.

Could this default to doing the whole file if no text is selected, or have a config option to work that way?  In trying to migrate over to vscode, this would be awesome.

**Comment by ryu1kn** [comment]
Hi @jgreer , thanks for heavily using the extension :smile:

I'm not sure if the default behaviour should be changed but definitely agree that there should at least be an option to pipe the whole contents to the command if no text is selected. Thanks for the suggestion :+1:

**Comment by ryu1kn** [comment]
Released as v1.0.0 :+1:

@jgreer Set `"editWithShell.processEntireTextIfNoneSelected": true` and you'll get what you wanted :wink:

**Comment by jgreer** [comment]
Awesome!  Works great.  Thanks so much!
