### ISSUE TITLE
`"editWithShell.processEntireTextIfNoneSelected": true` process entire text no matter what

### ISSUE THREAD

**Issue by johnnytemp** [ryu1kn/vscode-edit-with-shell#6]
The setting `"editWithShell.processEntireTextIfNoneSelected": true` always substitute whole file even if there is some selection.

VSCode version 1.27.1.

**Comment by ryu1kn** [comment]
Hi @johnnytemp , thanks for reporting it. I just confirmed it!

**Comment by ryu1kn** [comment]
The fix released as v1.0.1! @johnnytemp It would be great if you can confirm the fix 😉

**Comment by johnnytemp** [comment]
Confirmed it is fixed.  Thank you for the prompt fix!  :)

**Comment by ryu1kn** [comment]
Cool! Thanks for confirming it :+1:
