### ISSUE TITLE
FR: Run specific command

### ISSUE THREAD

**Issue by admiralbumblebee** [ryu1kn/vscode-edit-with-shell#7]
I have a need for running various shell commands on text. This extension offers that capability, but I would instead like to always run a specific shell command when executing a shortcut.

Would it be possible to add this capability to the extension?

**Comment by ryu1kn** [comment]
Hi @admiralbumblebee , sorry for my slow response, I was on holiday.

Would it suffice your needs if you can:

1. List those commands in your configuration
1. Invoke an extension command that let you choose one of the commands and execute it

**Comment by admiralbumblebee** [comment]
I think that would work.

My goal is to send a line of text to awk or a ruby one-liner to process.

**Comment by ryu1kn** [comment]
Published as v1.1.0! :tada:

I introduced 5 "quick commands". You can assign a keyboard shortcut to each of them. This way you need only one action to run your favourite command.

@admiralbumblebee it would be great if you can play with it and let me know whether it satisfies your needs. Feel free to reopen it if it's missing something.
