### ISSUE TITLE
WSL Bash doesn't work

### ISSUE THREAD

**Issue by erick2red** [ryu1kn/vscode-edit-with-shell#9]
Hi,

I went and changed the setting to use Bash from Windows Subsystem for Linux, then I tried a simple command and I'm getting an error.

Settings:
```json
{
    "editWithShell.shell.windows": "bash.exe",
    "editWithShell.shellArgs.windows": []
}
```

Command: `cut -d, -f3` (I also tried: `cut -d, -f3 | sort`. Didn't work either)

Error I'm seeing is: `/bin/bash: cut -d, -f3: No such file or directory`

My VSCode version is:

```
Version: 1.30.1 (user setup)
Commit: dea8705087adb1b5e5ae1d9123278e178656186a
Date: 2018-12-18T18:12:07.165Z
Electron: 2.0.12
Chrome: 61.0.3163.100
Node.js: 8.9.3
V8: 6.1.534.41
OS: Windows_NT x64 10.0.17763
```

The extension version is: `1.1.0`

**Comment by ryu1kn** [comment]
Hi @erick2red , thanks for your thorough report. You need to give `-c` to the bash args like so

```
    "editWithShell.shell.windows": "bash",
    "editWithShell.shellArgs.windows": [
        "-c"
    ],
```

While I was looking at it, I encountered a different issue, the extension seems to do nothing and I found that bash is no longer starting on my machine. Executing `bash` on the command prompt also gave this, even though I have Ubuntu installed.

```
C:\Users\ryuichi>bash
Windows Subsystem for Linux has no installed distributions.
Distributions can be installed by visiting the Microsoft Store:
https://aka.ms/wslstore
Press any key to continue...
```

If I "launch" Ubuntu from the Store app, then both the above command and the extension started working. Maybe I need to follow the below link to fix my Ubuntu installation.

https://stackoverflow.com/questions/44829878/trying-to-use-bash-on-windows-and-got-no-installed-distributions-message

Anyway, let me know how you went 😉

**Comment by erick2red** [comment]
Hi,

Now it works, sometimes, there are commands for which it's still not working, e.g.:

```sh
egrep -o "[a-f0-9]{8}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{12}"
```

PS: My setup works fine from the command line

**Comment by ryu1kn** [comment]
The command filters the text only when there is any match and does nothing otherwise. Is that what you're seeing?

If that's the case, that would probably be because `egrep` (or `grep`) ends with an error code if there is no match. And this extension replace the text only when a command finishes successfully.

Do you see any logs when you open dev tools (**Help > Toggle Developer Tools**) ?

**Comment by erick2red** [comment]
I tried, and it works, at times, some other times it doesn't work.
I've tried opening the Developer Tools, but nothing shows.

I'll report back if I see any pattern or spot the error.

**Comment by ryu1kn** [comment]
Cool thanks. I'm closing this for now then; please reopen it when you find it out more ;)
